---
title: "Thalamus Analysis"
author: "FG"
date: "5 3 2021"
output: 
  bookdown::html_document2:
    code_folding: hide
    toc: yes
    toc_depth: 5
    highlight: tango
    theme: paper
    fig_width: 20
    fig_height: 20
    fig_caption: yes
    number_sections: yes
    keep_md: yes
    df_print: default
---

```{r}
Sys.setenv(https_proxy="http://ukd-proxy:80")
```


```{r library, results='hide', message=FALSE, warning=FALSE} 
library(htmlTable)
library(rmarkdown)
library(Hmisc)
library(dplyr)
library(psych)
library(pastecs)
library(tidyr)
library(tidyverse)
library(ggplot2) # for data visualization (plotting)
library(car) # for statistical models (ANCOVA with type III errors), dummy coding
library(MatchIt)
library(ggforce) # extends functionality of ggplot2 (e.g. spreads boxplot facets (facet_wrap) over multiple pages)
library(cowplot)
library(ggsci) # alternative color tool/palettes for plotting (scientific journal style)
library(ggpubr) # extends functionality of ggplot2 (e.g. editing options for publication)
library(ggsignif)
library(kableExtra) # for creating kables (customized tables in RMarkdown output with styling options)
library(bookdown) # support for numbering figure and table captions
library(rstatix) 
library(MASS) # for robust linear model
library(broom) # tidy test output, e.g. of GLM
library(emmeans) # for estimated marginal means (EMM) (covariate-adjusted means in ANCOVA)
library(sfsmisc) 
library(scales)
library(sjstats)
library(sqldf)
```

### GLM 1 - adjusted for eTIV
```{r glmetiv, results="asis", message=FALSE, warning=FALSE}
options(contrasts = c("contr.sum", "contr.poly"))

ancova.etiv <- glmdata %>%
  mutate(point_of_research = relevel(as.factor(point_of_research), ref="HCW")) %>%
  nest(data = - c(region, hemi_region, labeller, group, hemi_group, group_labeller, region_type)) %>%
  mutate(
    lm = map(data, ~ lm(measure ~ point_of_research + e_tiv, data = .x, na.action = na.omit)),
    adj.means = map(lm, ~ emmeans(.x, "point_of_research")),
    tidymeans = map(adj.means, tidy),
    anova = map(lm, ~ car::Anova(.x, type="III", test.statistic="F")),
    anova_stats = map(anova, ~ sjstats::anova_stats(.x))) %>%
  unnest(anova_stats) %>%
  group_by(region_type, term) %>%
  mutate(p.adj = p.adjust(p.value, method="BH")) %>%
  mutate(p.adj = as.numeric(p.adj)) %>%
  mutate(is.signif = ifelse(p.adj<0.05, TRUE, FALSE)) %>%
  mutate(adj.signif = as.character(asterisk_function(p.adj))) %>%
  mutate(p.adj = formatC(p.adj, format="f", digits=4)) %>%
  mutate(p.value = formatC(p.value, format="f", digits=4)) %>%
  mutate(is.signif = ifelse(p.adj<0.05, TRUE, FALSE)) %>%
  ungroup() %>%
  dplyr::select(region, hemi_region, labeller, group, hemi_group, group_labeller, region_type, tidymeans, term, sumsq, df, statistic, p.value, p.adj, 
                adj.signif, is.signif, partial.etasq) %>%
  arrange(hemi_region) %>%
  mutate(hemi_region = as.character(hemi_region))

emmeans.etiv <- ancova.etiv %>%
  dplyr::select(hemi_region, region, labeller, tidymeans) %>%
  distinct(hemi_region, .keep_all=TRUE) %>%
  unnest(tidymeans) %>%
  dplyr::select(hemi_region, region, labeller, point_of_research, estimate, std.error)
``` 


```{r etivplot, fig.cap="Barplots for GLMs, adjusted for eTIV", echo=TRUE, message=FALSE, warning=FALSE}
bardata.etiv <- emmeans.etiv %>%
  group_by(region) %>% arrange(region, .by_group=TRUE) %>%
  mutate(point_of_research = dplyr::recode(point_of_research,
                                    "T1" = "AN",
                                    "HCW" = "HC"))

y.position.bar.etiv <- emmeans.etiv %>% 
  group_by(region) %>%
  arrange(desc(estimate), .by_group=TRUE) %>%
  slice_head(n = 1) %>%
  mutate(ymin = round((0.7*estimate)-2, -1)) %>%
  mutate(ymax = round((1.3*estimate)+2, -1)) %>%
  mutate(y.position = (0.8*(ymax-ymin))+ymin) %>%
  dplyr::select(region, y.position, ymin, ymax) %>%
  ungroup()

plotlist = list()

for (Region in unique(bardata.etiv$region)) {
  
  plotdata <- bardata.etiv %>% filter(region %in% Region)
  
  pvalues <- ancova.etiv %>%
    filter(term %in% "point_of_research") %>%
    filter(region %in% Region) %>%
    rename(point_of_research = term) %>%
    dplyr::select(region, hemi_region, labeller, point_of_research, adj.signif) %>%
    left_join(y.position.bar.etiv, by="region") %>%
    mutate(xmin = 1) %>%
    mutate(xmax = 2)
  
  yaxis <- y.position.bar.etiv %>%
    filter(region %in% Region)
  
  barplots <- plotdata %>%
    ggplot(aes(x=point_of_research, y=estimate, fill = point_of_research, color = point_of_research)) +
    geom_bar(stat="identity", color=NA, position=position_dodge()) +
    geom_errorbar(aes(ymin=estimate-std.error, ymax=estimate+std.error), width=0.2, size=1.0, color = "BLACK",
                 position=position_dodge(1)) +
    geom_signif(data=pvalues, aes(annotations = adj.signif, y_position = y.position, xmin = xmin, xmax = xmax), 
              tip_length = 0.05, textsize = 6, vjust = -0.45, color = "BLACK", manual = TRUE) +
    scale_y_continuous(breaks = pretty_breaks(n=3)) +
    coord_cartesian(ylim=c(yaxis$ymin, yaxis$ymax)) +
    scale_fill_jama(alpha=0.8) + scale_color_jama(alpha=0.8) +
    plot_theme_transparent2 + 
    theme(axis.title.x = element_blank(), axis.title.y = element_blank()) +
    theme(strip.text.x = element_text(size=15)) +
    guides(fill = FALSE, color = FALSE) +
    facet_wrap(~ labeller, scales="free_x", labeller = label_wrap_gen(width=15))
  
 plotlist[[Region]] = barplots
 
}

bp.whole.etiv <- plotlist$Whole_thalamus
bp.nuclei.etiv <- plotlist[1:25] 

barplotarrange.etiv <- ggarrange(bp.whole.etiv, 
          ggarrange(plotlist=bp.nuclei.etiv, ncol=5, nrow=5),
          ncol=2, widths=c(1,2)) %>%
  annotate_figure(left = text_grob("Volumes (EMM ± SEM) in mm^3", size=24, rot=90))

#barplotarrange.etiv

#ggsave(barplotarrange.etiv, filename="figures/barplots_glm_etiv.png", width=30, height=25, dpi=300)
```


### GLM 2 - adjusted for whole thalamus
```{r glmwhole, results="asis", message=FALSE, warning=FALSE}
ancova.whole <- glmdata %>%
filter(region %in% "Whole_thalamus") %>%
  dplyr::select(storage_name, hemi, measure) %>%
  rename(whole_thalamus = measure) %>% 
  right_join(glmdata, by=c("storage_name", "hemi")) %>%
  filter(region != "Whole_thalamus") %>%
  mutate(point_of_research = relevel(as.factor(point_of_research), ref="HCW")) %>%
  nest(data = - c(hemi_region, labeller, region, group, hemi_group, group_labeller, region_type)) %>%
  mutate(
    lm = map(data, ~ lm(measure ~ point_of_research + e_tiv + whole_thalamus, data = .x, na.action = na.omit)),
    adj.means = map(lm, ~ emmeans(.x, "point_of_research")),
    tidymeans = map(adj.means, tidy),
    anova = map(lm, ~ car::Anova(.x, type="III", test.statistic="F")),
    anova_stats = map(anova, ~ sjstats::anova_stats(.x))) %>%
  unnest(anova_stats) %>%
  group_by(term) %>%
  mutate(p.adj = p.adjust(p.value, method="BH")) %>%
  mutate(p.adj = as.numeric(p.adj)) %>%
  mutate(is.signif = ifelse(p.adj<0.05, TRUE, FALSE)) %>%
  mutate(adj.signif = as.character(asterisk_function(p.adj))) %>%
  mutate(p.adj = formatC(p.adj, format="f", digits=4)) %>%
  mutate(p.value = formatC(p.value, format="f", digits=4)) %>%
  mutate(is.signif = ifelse(p.adj<0.05, TRUE, FALSE)) %>%
  ungroup() %>%
  dplyr::select(region, hemi_region, labeller, group, hemi_group, group_labeller, region_type,tidymeans, term, sumsq, df, statistic, p.value, p.adj, 
                adj.signif, is.signif, partial.etasq) %>%
  arrange(hemi_region) %>%
  mutate(hemi_region = as.character(hemi_region))

emmeans.whole <- ancova.whole %>%
  dplyr::select(hemi_region, region, labeller, tidymeans) %>%
  distinct(hemi_region, .keep_all=TRUE) %>%
  unnest(tidymeans) %>%
  dplyr::select(hemi_region, region, labeller, point_of_research, estimate, std.error)
``` 

```{r wholeplot, fig.cap="Barplots for GLMs, adjusted for whole thalamus", echo=TRUE, message=FALSE, warning=FALSE}
bardata.whole <- emmeans.whole %>%
  group_by(region) %>% arrange(region, .by_group=TRUE) %>%
  mutate(point_of_research = dplyr::recode(point_of_research,
                                    "T1" = "AN",
                                    "HCW" = "HC"))

y.position.bar.whole <- emmeans.etiv %>% 
  group_by(region) %>%
  arrange(desc(estimate), .by_group=TRUE) %>%
  slice_head(n = 1) %>%
  mutate(ymin = round((0.7*estimate)-2, -1)) %>%
  mutate(ymax = round((1.3*estimate)+2, -1)) %>%
  mutate(y.position = (0.8*(ymax-ymin))+ymin) %>%
  dplyr::select(region, y.position, ymin, ymax) %>%
  ungroup()

plotlist = list()

for (Region in unique(bardata.whole$region)) {
  
  plotdata <- bardata.whole %>% filter(region %in% Region)
  
  pvalues <- ancova.whole %>%
    filter(term %in% "point_of_research") %>%
    filter(region %in% Region) %>%
    rename(point_of_research = term) %>%
    dplyr::select(region, hemi_region, labeller, point_of_research, adj.signif) %>%
    left_join(y.position.bar.whole, by="region") %>%
    mutate(xmin = 1) %>%
    mutate(xmax = 2)
  
  yaxis <- y.position.bar.whole %>%
    filter(region %in% Region)
  
  barplots <- plotdata %>%
    ggplot(aes(x=point_of_research, y=estimate, fill = point_of_research, color = point_of_research)) +
    geom_bar(stat="identity", color=NA, position=position_dodge()) +
    geom_errorbar(aes(ymin=estimate-std.error, ymax=estimate+std.error), width=0.2, size=1.0, color = "BLACK",
                 position=position_dodge(1)) +
    geom_signif(data=pvalues, aes(annotations = adj.signif, y_position = y.position, xmin = xmin, xmax = xmax), 
              tip_length = 0.05, textsize = 6, vjust = -0.45, color = "BLACK", manual = TRUE) +
    scale_y_continuous(breaks = pretty_breaks(n=3)) +
    coord_cartesian(ylim=c(yaxis$ymin, yaxis$ymax)) +
    scale_fill_jama(alpha=0.8) + scale_color_jama(alpha=0.8) +
    plot_theme_transparent2 + 
    theme(axis.title.x = element_blank(), axis.title.y = element_blank()) +
    theme(strip.text.x = element_text(size=15)) +
    guides(fill = FALSE, color = FALSE) +
    facet_wrap(~ labeller, scales="free_x", labeller = label_wrap_gen(width=15))
  
 plotlist[[Region]] = barplots
 
}

bp.nuclei.whole <- plotlist[1:25] 

barplotarrange.whole <- ggarrange(plotlist=bp.nuclei.whole, ncol=5, nrow=5) %>%
  annotate_figure(left = text_grob("Volumes (EMM ± SEM) in mm^3", size=24, rot=90))

#barplotarrange.whole

#ggsave(barplotarrange.whole, filename="figures/barplots_glm_whole.png", width=25, height=25, dpi=300)
```


### FDR correction ###########################################################################################################################

### FDR corection for GLM 1 (etiv) and GLM 2 (etiv + whole thal)
```{r padjustglm, results="asis", message=FALSE, warning=FALSE}
p.adjust.1 <- ancova.etiv %>%
  filter(term %in% "point_of_research") %>%
  mutate(main_glm = "GLM 1") %>%
  rename(point_of_research = term) %>%
  dplyr::select(main_glm, region, hemi_region, labeller, point_of_research, p.value, region_type)

p.adjust.2 <- ancova.whole %>%
  filter(term %in% "point_of_research") %>%
  mutate(main_glm = "GLM 2") %>%
  rename(point_of_research = term) %>%
  dplyr::select(main_glm, region, hemi_region, labeller, point_of_research, p.value, region_type)


p.combiadjust <- bind_rows(p.adjust.1, p.adjust.2) %>%
  group_by(region_type) %>% 
  mutate(p.adj.combi = p.adjust(p.value, method="BH")) %>%
  mutate(p.adj.combi = as.numeric(p.adj.combi)) %>%
  mutate(adj.signif.combi = as.character(asterisk_function(p.adj.combi)))  %>%
  ungroup()

ancova.etiv_fdr <- p.combiadjust %>%
  filter(main_glm == "GLM 1") %>%
  dplyr::select(hemi_region, p.adj.combi, adj.signif.combi) %>%
  full_join(ancova.etiv, by="hemi_region") %>%
  mutate(is.signif.combi = ifelse(p.adj.combi<0.05, TRUE, FALSE)) %>%
  mutate(p.adj.combi = formatC(p.adj.combi, format="f", digits=4)) %>%
  dplyr::select(-c(is.signif))

ancova.whole_fdr <- p.combiadjust %>%
  filter(main_glm == "GLM 2") %>%
  dplyr::select(hemi_region, p.adj.combi, adj.signif.combi) %>%
  full_join(ancova.whole, by="hemi_region")%>%
  mutate(is.signif.combi = ifelse(p.adj.combi<0.05, TRUE, FALSE)) %>% #why compute this?? #just base follow up analysis on one main GLM
  mutate(p.adj.combi = formatC(p.adj.combi, format="f", digits=4)) %>%
  dplyr::select(-c(is.signif))
```


### FDR corrected GLM 1 Bars
```{r etivplot, fig.cap="Barplots for GLMs, adjusted for eTIV and FDR", echo=TRUE, message=FALSE, warning=FALSE}

for (Region in unique(bardata.etiv$region)) {
  
  plotdata <- bardata.etiv %>% filter(region %in% Region)
  
  pvalues_fdr <- ancova.etiv_fdr %>%
    filter(term %in% "point_of_research") %>%
    filter(region %in% Region) %>%
    rename(point_of_research = term) %>%
    dplyr::select(region, hemi_region, labeller, point_of_research, adj.signif.combi) %>%
    left_join(y.position.bar.etiv, by="region") %>%
    mutate(xmin = 1) %>%
    mutate(xmax = 2)
  
  yaxis <- y.position.bar.etiv %>%
    filter(region %in% Region)
  
  barplots <- plotdata %>%
    ggplot(aes(x=point_of_research, y=estimate, fill = point_of_research, color = point_of_research)) +
    geom_bar(stat="identity", color=NA, position=position_dodge()) +
    geom_errorbar(aes(ymin=estimate-std.error, ymax=estimate+std.error), width=0.2, size=1.0, color = "BLACK",
                 position=position_dodge(1)) +
    geom_signif(data=pvalues_fdr, aes(annotations = adj.signif.combi, y_position = y.position, xmin = xmin, xmax = xmax), 
              tip_length = 0.05, textsize = 6, vjust = -0.45, color = "BLACK", manual = TRUE) +
    scale_y_continuous(breaks = pretty_breaks(n=3)) +
    coord_cartesian(ylim=c(yaxis$ymin, yaxis$ymax)) +
    scale_fill_jama(alpha=0.8) + scale_color_jama(alpha=0.8) +
    plot_theme_transparent2 + 
    theme(axis.title.x = element_blank(), axis.title.y = element_blank()) +
    theme(strip.text.x = element_text(size=15)) +
    guides(fill = FALSE, color = FALSE) +
    facet_wrap(~ labeller, scales="free_x", labeller = label_wrap_gen(width=15))
  
 plotlist[[Region]] = barplots
 
}

bp.whole.etiv_fdr <- plotlist$Whole_thalamus
bp.nuclei.etiv_fdr <- plotlist[1:25] 

barplotarrange.etiv_fdr <- ggarrange(bp.whole.etiv_fdr, 
          ggarrange(plotlist=bp.nuclei.etiv_fdr, ncol=5, nrow=5),
          ncol=2, widths=c(1,2)) %>%
  annotate_figure(left = text_grob("Volumes (EMM ± SEM) in mm^3", size=24, rot=90))

#barplotarrange.etiv_fdr

ggsave(barplotarrange.etiv_fdr, filename="figures/barplots_glm_etiv_fdr.png", width=30, height=25, dpi=300)
```

### FDR corrected GLM 2 Bars
```{r wholeplot, fig.cap="Barplots for GLMs, adjusted for whole thalamus", echo=TRUE, message=FALSE, warning=FALSE}
for (Region in unique(bardata.whole$region)) {
  
  plotdata <- bardata.whole %>% filter(region %in% Region)
  
  pvalues_fdr <- ancova.whole_fdr %>%
    filter(term %in% "point_of_research") %>%
    filter(region %in% Region) %>%
    rename(point_of_research = term) %>%
    dplyr::select(region, hemi_region, labeller, point_of_research, adj.signif.combi) %>%
    left_join(y.position.bar.whole, by="region") %>%
    mutate(xmin = 1) %>%
    mutate(xmax = 2)
  
  yaxis <- y.position.bar.whole %>%
    filter(region %in% Region)
  
  barplots <- plotdata %>%
    ggplot(aes(x=point_of_research, y=estimate, fill = point_of_research, color = point_of_research)) +
    geom_bar(stat="identity", color=NA, position=position_dodge()) +
    geom_errorbar(aes(ymin=estimate-std.error, ymax=estimate+std.error), width=0.2, size=1.0, color = "BLACK",
                 position=position_dodge(1)) +
    geom_signif(data=pvalues_fdr, aes(annotations = adj.signif.combi, y_position = y.position, xmin = xmin, xmax = xmax), 
              tip_length = 0.05, textsize = 6, vjust = -0.45, color = "BLACK", manual = TRUE) +
    scale_y_continuous(breaks = pretty_breaks(n=3)) +
    coord_cartesian(ylim=c(yaxis$ymin, yaxis$ymax)) +
    scale_fill_jama(alpha=0.8) + scale_color_jama(alpha=0.8) +
    plot_theme_transparent2 + 
    theme(axis.title.x = element_blank(), axis.title.y = element_blank()) +
    theme(strip.text.x = element_text(size=15)) +
    guides(fill = FALSE, color = FALSE) +
    facet_wrap(~ labeller, scales="free_x", labeller = label_wrap_gen(width=15))
  
 plotlist[[Region]] = barplots
 
}

bp.nuclei.whole_fdr <- plotlist[1:25] 

barplotarrange.whole_fdr <- ggarrange(plotlist=bp.nuclei.whole_fdr, ncol=5, nrow=5) %>%
  annotate_figure(left = text_grob("Volumes (EMM ± SEM) in mm^3", size=24, rot=90))

#barplotarrange.whole_fdr

ggsave(barplotarrange.whole_fdr, filename="figures/barplots_glm_whole_fdr.png", width=25, height=25, dpi=300)
```

### Robust regression models ############# using only significant nuclei from GLM 1 & 2 ########################################################


## RLM1: etiv and age as covariables for predictor, 
## Predictor: ZWANG
```{r robustregressionnuclei, results="asis", message=FALSE, warning=FALSE}
sample_regression <- sample %>%
dplyr::select(storage_name, resultquest_scl90r_skazwang)

cordata.rlm1 <- ancova.etiv_fdr %>%
  filter(term == "point_of_research") %>%
  dplyr::select(hemi_region, is.signif.combi) %>%
  right_join(glmdata, by="hemi_region") %>%
  mutate(hemi_region = factor(hemi_region, levels=c('lh_Whole_thalamus','rh_Whole_thalamus',
                                                   'lh_AV','rh_AV',
                                                   'lh_LD','rh_LD',
                                                   'lh_LP','rh_LP',
                                                   'lh_VA','rh_VA',
                                                   'lh_VAmc','rh_VAmc',
                                                   'lh_VLa','rh_VLa',
                                                   'lh_VLp','rh_VLp',
                                                   'lh_VPL','rh_VPL',
                                                   'lh_VM','rh_VM',
                                                   'lh_CeM','rh_CeM',
                                                   'lh_CL','rh_CL',
                                                   'lh_Pc','rh_Pc',
                                                   'lh_CM','rh_CM',
                                                   'lh_Pf','rh_Pf',
                                                   'lh_Pt','rh_Pt',
                                                   'lh_MV(Re)','rh_MV(Re)',
                                                   'lh_MDm','rh_MDm',
                                                   'lh_MDl','rh_MDl',
                                                   'lh_LGN','rh_LGN',
                                                   'lh_MGN','rh_MGN',
                                                   'lh_L-Sg','rh_L-Sg',
                                                   'lh_PuA','rh_PuA',
                                                   'lh_PuM','rh_PuM',
                                                   'lh_PuL','rh_PuL',
                                                   'lh_PuI','rh_PuI'))) %>%
  filter(point_of_research %in% "T1") %>%
  filter(is.signif.combi == TRUE) %>% #JS: just base on one main GLM?
  filter(region != "Whole_thalamus") %>%
  left_join(sample_regression, by="storage_name") %>% 
  dplyr::select(storage_name, 
                hemi_region, 
                labeller, 
                age_at_date_of_research, 
                e_tiv, 
                measure, 
                resultquest_scl90r_skazwang) %>%
  pivot_longer(-c(storage_name, hemi_region, labeller, age_at_date_of_research, e_tiv, measure), 
               names_to = "scale", values_to = "value") #%>%
  nest(-c(hemi_region, labeller, scale)) %>%
  mutate(
    rlm = map(data, ~ rlm(value ~ measure + age_at_date_of_research + e_tiv, data=.x, na.action = na.omit)),
    tidyrlm = map(rlm, tidy),
    tidyrlm = map(tidyrlm, ~ rename(.x, t.value = statistic)),
    testrlm = map(rlm, ~ f.robftest(.x, var = "measure")),
    tidytestrlm = map(testrlm, tidy),
    tidytestrlm = map(tidytestrlm, ~ rename(.x, F.value = statistic)),
    filterrlm = map(tidyrlm, ~ filter(.x, term %in% "measure"))) %>%
  unnest(tidytestrlm, filterrlm) %>%
  mutate(unadj.signif = as.character(asterisk_function(p.value))) %>%
  mutate(p.adj = p.adjust(p.value, method="BH")) %>%
  mutate(adj.signif = as.character(asterisk_function(p.adj))) %>%
  dplyr::select(hemi_region, labeller, scale, t.value, p.value, unadj.signif, p.adj, adj.signif) %>%
  mutate(p.value = formatC(p.value, format="f", digits=3)) %>%
  mutate(p.adj = formatC(p.adj, format="f", digits=3)) %>% ## adjusted digits of adjusted p value.
  mutate(t.value = formatC(t.value, format="f", digits=3)) %>% ## adjusted digits of adjusted t value.
  nest(-c(hemi_region, labeller, scale)) %>%
  group_by(hemi_region) %>%
  pivot_wider(names_from = "scale", values_from = "data") %>%
  unnest(resultquest_scl90r_skazwang)  %>%
  arrange(hemi_region) %>%
  mutate(hemi_region = as.character(hemi_region)) %>%
  # mutate(variables_group = dplyr::recode(hemi_region, !!!variables_grouper.glm, .default = "missing group")) %>%
  ungroup()

write.csv(cordata.rlm1,"tables/RLM1+ZWANG_signinuclei_fromGLM.csv", row.names = FALSE)


# cordata.rlm1 %>%
#   dplyr::select(-c(hemi_region, variables_group)) %>%
#   knitr::kable(format = "html", digits=2, align = "l", col.names=c("Thalamus (sub-)regions (GLM adj. whole thalamus, p.adj<0.05)", rep(c("t", "p", "Unadj. signif.", "p.adj", "Adj. signif."), 1)), caption = "Robust regression models in acAN-T1 (adjusted for participant age and eTIV)") %>%
#   kable_paper(bootstrap_options="striped", full_width=FALSE, position="left", html_font="Arial", font_size="10") %>%
#   add_header_above(c(" ", "Thalamus ~ SCL-90-R GSI"=5), align="l") %>%
#   pack_rows(index = table(fct_inorder(cordata.rlm1$variables_group))) %>%
#   save_kable(file="tables/thalamus_RLM1_FDR.png", zoom=5)
```

## RLM2: etiv and age as covariables for predictor, 
## Predictor: ZWANG
```{r robustregressionnuclei, results="asis", message=FALSE, warning=FALSE}
sample_regression <- sample %>%
dplyr::select(storage_name, resultquest_scl90r_skazwang)

cordata.rlm1 <- ancova.etiv_fdr %>%
  filter(term == "point_of_research") %>%
  dplyr::select(hemi_region, is.signif.combi) %>%
  right_join(glmdata, by="hemi_region") %>%
  mutate(hemi_region = factor(hemi_region, levels=c('lh_Whole_thalamus','rh_Whole_thalamus',
                                                   'lh_AV','rh_AV',
                                                   'lh_LD','rh_LD',
                                                   'lh_LP','rh_LP',
                                                   'lh_VA','rh_VA',
                                                   'lh_VAmc','rh_VAmc',
                                                   'lh_VLa','rh_VLa',
                                                   'lh_VLp','rh_VLp',
                                                   'lh_VPL','rh_VPL',
                                                   'lh_VM','rh_VM',
                                                   'lh_CeM','rh_CeM',
                                                   'lh_CL','rh_CL',
                                                   'lh_Pc','rh_Pc',
                                                   'lh_CM','rh_CM',
                                                   'lh_Pf','rh_Pf',
                                                   'lh_Pt','rh_Pt',
                                                   'lh_MV(Re)','rh_MV(Re)',
                                                   'lh_MDm','rh_MDm',
                                                   'lh_MDl','rh_MDl',
                                                   'lh_LGN','rh_LGN',
                                                   'lh_MGN','rh_MGN',
                                                   'lh_L-Sg','rh_L-Sg',
                                                   'lh_PuA','rh_PuA',
                                                   'lh_PuM','rh_PuM',
                                                   'lh_PuL','rh_PuL',
                                                   'lh_PuI','rh_PuI'))) %>%
  filter(point_of_research %in% "T1") %>%
  filter(is.signif.combi == TRUE) %>% #JS: just base on one main GLM?
  filter(region != "Whole_thalamus") %>%
  left_join(sample_regression, by="storage_name") %>% 
  dplyr::select(storage_name, 
                hemi_region, 
                labeller, 
                age_at_date_of_research, 
                e_tiv, 
                measure, 
                resultquest_scl90r_skazwang) %>%
  pivot_longer(-c(storage_name, hemi_region, labeller, age_at_date_of_research, e_tiv, measure), 
               names_to = "scale", values_to = "value") #%>%
  nest(-c(hemi_region, labeller, scale)) %>%
  mutate(
    rlm = map(data, ~ rlm(value ~ measure + age_at_date_of_research + e_tiv, data=.x, na.action = na.omit)),
    tidyrlm = map(rlm, tidy),
    tidyrlm = map(tidyrlm, ~ rename(.x, t.value = statistic)),
    testrlm = map(rlm, ~ f.robftest(.x, var = "measure")),
    tidytestrlm = map(testrlm, tidy),
    tidytestrlm = map(tidytestrlm, ~ rename(.x, F.value = statistic)),
    filterrlm = map(tidyrlm, ~ filter(.x, term %in% "measure"))) %>%
  unnest(tidytestrlm, filterrlm) %>%
  mutate(unadj.signif = as.character(asterisk_function(p.value))) %>%
  mutate(p.adj = p.adjust(p.value, method="BH")) %>%
  mutate(adj.signif = as.character(asterisk_function(p.adj))) %>%
  dplyr::select(hemi_region, labeller, scale, t.value, p.value, unadj.signif, p.adj, adj.signif) %>%
  mutate(p.value = formatC(p.value, format="f", digits=3)) %>%
  mutate(p.adj = formatC(p.adj, format="f", digits=3)) %>% ## adjusted digits of adjusted p value.
  mutate(t.value = formatC(t.value, format="f", digits=3)) %>% ## adjusted digits of adjusted t value.
  nest(-c(hemi_region, labeller, scale)) %>%
  group_by(hemi_region) %>%
  pivot_wider(names_from = "scale", values_from = "data") %>%
  unnest(resultquest_scl90r_skazwang)  %>%
  arrange(hemi_region) %>%
  mutate(hemi_region = as.character(hemi_region)) %>%
  # mutate(variables_group = dplyr::recode(hemi_region, !!!variables_grouper.glm, .default = "missing group")) %>%
  ungroup()

write.csv(cordata.rlm1,"tables/RLM2+LEPTIN_signinuclei+fromGLM", row.names = FALSE)
```


```{r robustregressionnuclei, results="asis", message=FALSE, warning=FALSE}
<!-- ## find relatively larger/smaller nuclei in AN and HC ######################################################## -->

<!-- ## atrophy function -->
<!-- ```{r} -->
<!-- # x = bardata.etiv or bardata.whole -->
<!-- atrophy_function <- function(x) { -->
<!--   a <- (x)%>% -->
<!--     filter(point_of_research == "HC")%>% -->
<!--     rename(HC_estimate = estimate)%>% -->
<!--     dplyr::select(-c("point_of_research", "std.error")) -->

<!--   (x)%>% -->
<!--     filter(point_of_research == "AN")%>% -->
<!--     rename(AN_estimate = estimate)%>% -->
<!--     dplyr::select(-c("point_of_research", "std.error"))%>% -->
<!--     full_join(a, by =c("hemi_region", "region", "labeller"))%>% -->
<!--     mutate(delta.estimate = HC_estimate-AN_estimate)%>% -->
<!--     mutate(volume.difference = ifelse(delta.estimate > 0, "relative nucleus volume is lower in AN",  -->
<!--                                     ifelse(delta.estimate < 0, "relative nucleus volume is higher in AN", "no volume differences")))%>% -->
<!--     dplyr::select(-c("HC_estimate","AN_estimate")) -->
<!-- } -->
<!-- ``` -->

<!-- ## build table with results of both GLMs and atrophy differences -->
<!-- ```{r} -->
<!--  GLM1.result.table <- ancova.etiv_fdr%>% -->
<!--   dplyr::select(hemi_region, region, labeller, group, term, p.adj.combi, adj.signif.combi, is.signif.combi)%>% -->
<!--   filter(term %in% "point_of_research") %>% -->
<!--   dplyr::select(-c(term))%>% -->
<!--   rename(p.etiv = p.adj.combi)%>% -->
<!--   rename(signif.etiv = adj.signif.combi)%>% -->
<!--   rename(is.signif.etiv = is.signif.combi)%>% -->
<!--   full_join(atrophy_function(bardata.etiv), by =c("hemi_region", "region", "labeller"))%>% -->
<!--   filter(region != "Whole_thalamus")%>%  -->
<!--   rename(volume.difference.etiv = volume.difference)%>% -->
<!--   rename(delta.estimate.etiv = delta.estimate) -->

<!--  GLM2.result.table <- ancova.whole_fdr%>% -->
<!--   dplyr::select(hemi_region, region, labeller, group, term, p.adj.combi, adj.signif.combi, is.signif.combi)%>% -->
<!--   filter(term %in% "point_of_research") %>% -->
<!--   dplyr::select(-c(term))%>% -->
<!--   rename(p.whole = p.adj.combi)%>% -->
<!--   rename(signif.whole = adj.signif.combi)%>% -->
<!--   rename(is.signif.whole = is.signif.combi)%>% -->
<!--   full_join(atrophy_function(bardata.whole), by =c("hemi_region", "region", "labeller"))%>% -->
<!--   filter(region != "Whole_thalamus")%>%  -->
<!--   rename(volume.difference.whole = volume.difference)%>% -->
<!--   rename(delta.estimate.whole = delta.estimate) -->

<!--  GLM1.2.result.table <- ancova.whole_fdr %>% -->
<!--   dplyr::select(hemi_region, region, labeller, group, term, p.adj.combi, adj.signif.combi, is.signif.combi)%>% -->
<!--   filter(term %in% "point_of_research") %>% -->
<!--   dplyr::select(-c(term))%>% -->
<!--   rename(p.whole = p.adj.combi)%>% -->
<!--   rename(signif.whole = adj.signif.combi)%>% -->
<!--   rename(is.signif.whole = is.signif.combi)%>% -->
<!--   full_join(atrophy_function(bardata.whole), by =c("hemi_region", "region", "labeller"))%>% -->
<!--   rename(volume.difference.whole = volume.difference)%>% -->
<!--   rename(delta.estimate.whole = delta.estimate) %>% -->
<!--   inner_join(GLM1.result.table, by = c("hemi_region", "region","group", "labeller"))%>% -->
<!--   dplyr::select(-c(hemi_region))# %>% -->
<!--   write.csv2("tables/GLM1+2_results_FDR_C.csv", row.names = FALSE) -->
<!-- ``` -->

<!-- ##Sort GLM 1 + 2: results by hemi -->
<!-- ```{r} -->
<!-- build_RH <- GLM1.2.result.table%>% -->
<!--   dplyr::select(region,  -->
<!--                 group,  -->
<!--                 labeller, -->
<!--                 p.etiv, -->
<!--                 signif.etiv, -->
<!--                 is.signif.etiv, -->
<!--                 volume.difference.etiv, -->
<!--                 p.whole, -->
<!--                 signif.whole, -->
<!--                 is.signif.whole, -->
<!--                 volume.difference.whole) %>% -->
<!--   filter(grepl("rh", labeller))%>% -->
<!--   mutate( -->
<!--     RH_nucleus = ifelse(grepl("rh", labeller), labeller, "NA"), -->
<!--     nucleus = str_remove_all(RH_nucleus," rh"), -->
<!--     RH_p.etiv = ifelse(grepl("rh", labeller), p.etiv, "NA"), -->
<!--     RH_signi.etiv = ifelse(grepl("rh", labeller), signif.etiv, "NA"), -->
<!--     RH_p.whole = ifelse(grepl("rh", labeller), p.whole, "NA"), -->
<!--     RH_signi.whole = ifelse(grepl("rh", labeller), signif.whole, "NA"))%>% -->
<!--   rename( -->
<!--     RH_is.signif.etiv = is.signif.etiv, -->
<!--     RH_is.signif.whole = is.signif.whole, -->
<!--     RH_volume.difference.whole = volume.difference.whole, -->
<!--     RH_volume.difference.etiv = volume.difference.etiv)%>% -->
<!--   dplyr::select(region, group, nucleus, RH_p.etiv, RH_signi.etiv, RH_is.signif.etiv, RH_volume.difference.etiv, RH_p.whole, RH_signi.whole, RH_is.signif.whole, RH_volume.difference.whole) -->

<!-- GLM1.2.hemi <- GLM1.2.result.table%>% -->
<!--   dplyr::select(region, -->
<!--                 group,  -->
<!--                 labeller, -->
<!--                 p.etiv, -->
<!--                 signif.etiv, -->
<!--                 is.signif.etiv, -->
<!--                 volume.difference.etiv, -->
<!--                 p.whole, -->
<!--                 signif.whole, -->
<!--                 is.signif.whole, -->
<!--                 volume.difference.whole) %>% -->
<!--   filter(grepl("lh", labeller))%>% -->
<!--   mutate( -->
<!--     LH_nucleus = ifelse(grepl("lh", labeller), labeller, "NA"), -->
<!--     nucleus = str_remove_all(LH_nucleus," lh"), -->
<!--     LH_p.etiv = ifelse(grepl("lh", labeller), p.etiv, "NA"), -->
<!--     LH_signi.etiv = ifelse(grepl("lh", labeller), signif.etiv, "NA"), -->
<!--     LH_p.whole = ifelse(grepl("lh", labeller), p.whole, "NA"), -->
<!--     LH_signi.whole = ifelse(grepl("lh", labeller), signif.whole, "NA"))%>% -->
<!--   rename( -->
<!--     LH_is.signif.etiv = is.signif.etiv, -->
<!--     LH_is.signif.whole = is.signif.whole, -->
<!--     LH_volume.difference.whole = volume.difference.whole, -->
<!--     LH_volume.difference.etiv = volume.difference.etiv)%>% -->
<!--   dplyr::select(region, group, nucleus, LH_p.etiv, LH_signi.etiv, LH_is.signif.etiv, LH_volume.difference.etiv, LH_p.whole, LH_signi.whole, LH_is.signif.whole, LH_volume.difference.whole)%>% -->
<!--   full_join(build_RH, by = c("region", "group", "nucleus"))#%>% -->
<!--   write.csv2("tables/GLM1+2_results_FDR_hemi_C.csv", row.names = FALSE) -->

<!-- ``` -->